# Generated by Django 3.2.9 on 2021-11-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20211105_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectionprocess',
            name='teams',
            field=models.ManyToManyField(to='base.Team'),
        ),
    ]
